{
 "title": "DIYrobocars-RacingDashboard-V4_RACE-MONITOR",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1> DIYrobocars Virtual Racing League</h1>\n<h4> Parking Lot Nerds: Ann Arbor, Detroit, Ottawa, Stuttgart </h4>\n<small><small><small><small><small><small>   Rainer Bareiß, May 3rd, 2020 powered by InfluxDB, Grafana </small></small></small></small></small></small>"
   }
  },
  {
   "title": "records",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "istep" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "steering_angle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "select * from demo",
     "select": [
      [
       { "params": [ "user/angle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "throttle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "select * from demo",
     "select": [
      [
       { "params": [ "user/throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "select * from demo",
     "select": [
      [
       { "params": [ "pos/speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "pos/speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 3 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "pos/speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "user/angle histogram",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "user/angle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "pos/pos_x,y,z",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 8 },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "pos/pos_x" ], "type": "field" }
      ],
      [
       { "params": [ "pos/pos_z" ], "type": "field" }
      ],
      [
       { "params": [ "pos/speed" ], "type": "field" }
      ],
      [
       { "params": [ "user/throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "vel/vel_x,y,z",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "SELECT \"wheelEncoderLF\", \"wheelEncoderLR\", \"wheelEncoderRF\", \"wheelEncoderRR\" FROM \"DonkeySimulator\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "vel/vel_x" ], "type": "field" }
      ],
      [
       { "params": [ "vel/vel_y" ], "type": "field" }
      ],
      [
       { "params": [ "vel/vel_z" ], "type": "field" }
      ],
      [
       { "params": [ "wheelEncoderRR" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "user/throttle histogram",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "user/throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "gyro/gyro_x,y,z",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rotrads" } },
   "yaxes": [
    { "format": "rotrads" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "gyro/gyro_x" ], "type": "field" }
      ],
      [
       { "params": [ "gyro/gyro_y" ], "type": "field" }
      ],
      [
       { "params": [ "gyro/gyro_z" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "user/angle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "user/angle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "user/throttle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "user/throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "pilot/angle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "pilot/angle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "pilot/throttle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "pilot/throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "accel/accel_x,y,z",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "accMS2" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "accel/accel_x" ], "type": "field" }
      ],
      [
       { "params": [ "accel/accel_y" ], "type": "field" }
      ],
      [
       { "params": [ "accel/accel_z" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}